### ISSUE TITLE
Issues in Dynamo 2.16.1 and Revit 2023 Python 3 related

### ISSUE THREAD

**Issue by doctasayas** [andydandy74/ClockworkForDynamo#359]
**Describe the bug**
Clockwork Nodes for  "All Families Of Category," "Element.SetName," and probably other return null in Revit 2023 

**Steps to Reproduce**
See screent shot- This script works in 2022. It does not work in 2023 I have the Iron Python Package for 2023.

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: Windows 10
- Revit version: 2023
- Dynamo version: 2.16.1
- Clockwork version: 2.x

![Screenshot 2023-03-16 143455](https://user-images.githubusercontent.com/104386181/225720250-1d458c00-bd31-41f7-8a4c-0b202623db7d.png)

**Comment by andydandy74** [comment]
Can you confirm you're running these package versions:
- Clockwork for Dynamo 2.x v2.4.0
- DynamoIronPython2.7 v2.5.0

If not, you'll need to first update those packages and try running the graph again, 

If the issue only occurs when you re-run a graph, it is likely caused by a bug that has already been fixed but not yet been published (see https://github.com/andydandy74/ClockworkForDynamo/wiki/Version-History#bug-fixes). In that case you can download the updated nodes from this repository (they live here: https://github.com/andydandy74/ClockworkForDynamo/tree/master/nodes/2.x).

**Comment by doctasayas** [comment]
I'm Currently running:
Clockwork for Dynamo 2.4.0
DynamoIronPython 2.4.0 

upgrading Iron Python to  2.5.0 now

**Comment by doctasayas** [comment]
It still wasn't working with DynamoIronPython 2.5.0- The problem was IT department for my company was blocking part of the installation. 

I went through the same thing on my home PC and it works fine.

**Comment by andydandy74** [comment]
Glad to hear it's working now
